### ISSUE TITLE
Activity2 RuntimeException

### ISSUE THREAD

**Issue by daeun1012** [googlecodelabs/motionlayout#3]
I ran Step2(activity_step_2), but it occured runtimeexception.

My Device is
Model : SM-G920L
OS Version : 7.0 (API 24)

2019-06-18 14:04:20.056 1801-1801/com.google.samples.motionlayoutcodelab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.samples.motionlayoutcodelab, PID: 1801
    java.lang.RuntimeException: Canvas: trying to draw too large(167961600bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1420)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.view.View.getDrawableRenderNode(View.java:18591)
        at android.view.View.drawBackground(View.java:18527)
        at android.view.View.draw(View.java:18315)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at com.android.internal.policy.DecorView.draw(DecorView.java:919)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3139)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2935)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2527)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1526)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7102)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by dongzhixuanyuan** [comment]
I meet this crash problem too.
The reason is background.png is too large in drawable folder, so the solution is to create a drawable-xxxhdpi directory and put the background.png into this directory.

**Comment by objcode** [comment]
Ahoy! Thanks for the report – I resized the images and moved things around. It works when I try to reproduce, but please re-open if there's still an issue!

**Comment by HamzaMihfad** [comment]
Thank you dongzhixuanyuan, This fixed my issue
